name: check_code_quality
on: pull_request
jobs:
  black:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.9
      - run: |
          python -m pip install --upgrade pip
          pip install black
          pip install pylint
          pip install isort
      - run: |
          black --check --code --verbose
          pylint --check --code --verbose
          isort --check --code --verbose